### ISSUE TITLE
Credit RU theme/author in css files

### ISSUE THREAD

**Issue by jvcasillas** [andrewcparnell/how_to_publish_a_paper#1]
Hello, 

I enjoyed your slides and noticed that you used my css template ([ru_xaringan](https://github.com/jvcasillas/ru_xaringan), which is also one of the default templates included in the `xaringan` package). I was hoping that you could include the original author information in the css file (maynooth.css, line 3), which appears to have been removed in lieu of somebody else's name. If the css files were adapted to your own taste, which does not appear to be the case, please include a line stating that your template was adapted from `ru_xaringan`. Thank you for your understanding.

**Comment by jvcasillas** [comment]
@brunaw do you think you could help out with this?

**Comment by brunaw** [comment]
Hi @jvcasillas! Yes, definitely! Sorry about that, it was a lack of attention from my part. 

I will put your name as the author, linking to the original theme and a little bit about the adaptations made, would that be the best way to do it?

**Comment by jvcasillas** [comment]
That would be perfect. Thank you!
